name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unittests
        run: python -m unittest test/test_modules.py
      - name: Check status
        run: echo "✅" if ${{ steps.run.outputs.return_code }} == 0 else echo "❌"
        